// Front-End Frameworks/Vue/ecommerce-Frond-End/src/components/core/Product/Product.vue
<template>
  <div class="col-sm-4">
    <div class="product-image-wrapper">
      <div class="single-products">
        <div class="productinfo text-center">
          <img :src="product.imageUrl" :alt="product.title" />
          <h2>{{ product.price }}</h2>
          <p>{{ product.title }}</p>
          <router-link
            :to="'/product/' + product._id"
            class="btn btn-default add-to-cart"
          >
            <i class="fa fa-shopping-cart"></i>
            Product details
          </router-link>
        </div>
        <!-- <div v-fi="!!isLoggedIn" class="product-overlay">
          <div class="overlay-content">
            <h2>{{ product.price }}</h2>
            <p>{{ product.title }}</p>
            <router-link
              :to="['/product/', product._id]"
              class="btn btn-default add-to-cart"
              ><i class="fa fa-shopping-cart"></i>Product Details</router-link
            >
            <a
              (click)="deleteProduct(product._id)"
              class="btn btn-default add-to-cart"
              ><i class="fa fa-shopping-cart"></i>Delete {{ product.title }}</a
            >
          </div>
        </div> -->
      </div>
      <div class="choose">
        <ul class="nav nav-pills nav-justified">
          <li>
            <a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a>
          </li>
          <li>
            <a href="#"><i class="fa fa-plus-square"></i>Add to compare</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>

<script src="./Product.js"></script>

<style scoped src="./Product.scss" lang="scss"></style>

// Front-End Frameworks/Angular/ecommerce-Front-End/e-commerce/src/app/core/product/product.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Product } from 'src/app/shared/interfaces';

@Component({
  selector: 'app-product',
  templateUrl: './product.component.html',
  styleUrls: ['./product.component.scss']
})
export class ProductComponent implements OnInit {
  @Input() product: Product;

  constructor() {
  }

  ngOnInit() {
  }

}

<div class="col-sm-4">
  <div class="product-image-wrapper">
    <div class="single-products">
      <div class="productinfo text-center">
        <img src={{product.imageUrl}} alt={{product.title}} />
        <h2>{{product.price}}</h2>
        <p>{{product.title}}</p>
        <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
      </div>
      <div class="product-overlay">
        <div class="overlay-content">
          <h2>{{product.price}}</h2>
          <p>{{product.title}}</p>
          <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
        </div>
      </div>
    </div>
    <div class="choose">
      <ul class="nav nav-pills nav-justified">
        <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
        <li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
      </ul>
    </div>
  </div>
</div>
