// Front-End Frameworks/Vue/ecommerce-Frond-End/src/components/core/FeaturesItems/FeaturesItems.vue
<template>
  <div class="features_items" *ngIf="allProducts">
    <h2 class="title text-center">Features Items</h2>
    <!-- <ng-container *ngIf="allProducts">
      <ng-container *ngFor="let product of allProducts">
        <app-product
          *ngIf="product.featuredItem"
          [product]="product"
        ></app-product>
      </ng-container>
    </ng-container> -->
    <!-- <ng-container *ngIf="!allProducts">
      <h3 class="title text-center">
        No featured items are available at the moment!
      </h3>
    </ng-container> -->
  </div>
</template>

<script src="./FeaturesItems.js"></script>

<style scoped src="./FeaturesItems.scss" lang="scss"></style>

// Front-End Frameworks/Angular/ecommerce-Front-End/e-commerce/src/app/core/features-items/features-items.component.ts
import { Component, OnInit, Input, Output } from '@angular/core';
import { Product } from 'src/app/shared/interfaces';

@Component({
  selector: 'app-features-items',
  templateUrl: './features-items.component.html',
  styleUrls: ['./features-items.component.scss']
})
export class FeaturesItemsComponent implements OnInit {
  @Input() allProducts: Product[];

  constructor() { }

  ngOnInit() {
  }

}

<div class="features_items" *ngIf="allProducts">
  <h2 class="title text-center">Features Items</h2>
  <ng-container *ngIf="allProducts">
    <ng-container *ngFor="let product of allProducts">
      <app-product *ngIf="product.featuredItem" [product]="product"></app-product>
    </ng-container>
  </ng-container>
  <ng-container *ngIf="!allProducts">
    <h3 class="title text-center">No featured items are available at the moment!</h3>
  </ng-container>
</div>
