// Front-End Frameworks/Vue/ecommerce-Frond-End/src/components/core/Slider/Slider.vue
<template>
  <div>
    <template v-if="!allProducts">
      <span>No products to display in the slider section!</span>
    </template>
    <template v-if="allProducts">
      <section id="slider">
        <div class="container">
          <div class="row">
            <div class="col-sm-12">
              <div
                id="slider-carousel"
                class="carousel slide"
                data-ride="carousel"
              >
                <ol class="carousel-indicators">
                  <template
                    v-for="(product, num) in allProducts"
                    :key="product._id"
                  >
                    <template v-if="product.onSlider">
                      <li
                        attr.data-slide-to="num"
                        data-target="#slider-carousel"
                      >
                        {{ num }}
                      </li>
                      <!-- <li
                        :attr.data-slide-to="num"
                        data-target="#slider-carousel"
                        [class.active]="num===0"
                         routerLinkActive="active"
                      ></li> -->
                    </template>
                  </template>
                </ol>
                <div class="carousel-inner">
                  <template
                    *ngFor="let product of allProducts; let num = index;"
                  >
                    <template v-if="product.onSlider === true">
                      <div
                        class="item"
                        [class.active]="num===0"
                        routerLinkActive="active"
                      >
                        <div class="col-sm-6">
                          <h1><span>E</span>-SHOPPER</h1>
                          <h2>{{ product.title }}</h2>
                          <p>{{ product.description }}</p>
                          <button type="button" class="btn btn-default get">
                            Get it now
                          </button>
                        </div>
                        <div class="col-sm-6">
                          <img
                            src="{{product.imageUrl}}"
                            class="girl img-responsive"
                            alt=""
                          />
                        </div>
                      </div>
                    </template>
                  </template>
                </div>
                <a
                  href="#slider-carousel"
                  class="left control-carousel hidden-xs"
                  data-slide="prev"
                >
                  <i class="fa fa-angle-left"></i>
                </a>
                <a
                  href="#slider-carousel"
                  class="right control-carousel hidden-xs"
                  data-slide="next"
                >
                  <i class="fa fa-angle-right"></i>
                </a>
              </div>
            </div>
          </div>
        </div>
      </section>
    </template>
  </div>
</template>

<script src="./Slider.js"></script>

<style src="./Slider.scss" lang="scss"></style>

// Front-End Frameworks/Angular/ecommerce-Front-End/e-commerce/src/app/core/slider/slider.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Product } from 'src/app/shared/interfaces';

@Component({
  selector: 'app-slider',
  templateUrl: './slider.component.html',
  styleUrls: ['./slider.component.scss']
})
export class SliderComponent implements OnInit {
  @Input() product: Product;
  @Input() allProducts: Product[];

  constructor() { }

  ngOnInit() {
  }

}

<ng-container *ngIf="!allProducts">
  <span>No products to display in the slider section!</span>
</ng-container>
<ng-container *ngIf="allProducts">
  <section id="slider">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <div id="slider-carousel" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
              <ng-container *ngFor="let product of allProducts; let num = index;">
                <ng-container *ngIf="product.onSlider">
                  <li attr.data-slide-to="{{num}}" data-target="#slider-carousel" [class.active]="num===0"
                    routerLinkActive='active'></li>
                </ng-container>
              </ng-container>
            </ol>
            <div class="carousel-inner">
              <ng-container *ngFor="let product of allProducts; let num = index;">
                <ng-container *ngIf="product.onSlider===true">
                  <div class="item" [class.active]="num===0" routerLinkActive='active'>
                    <div class="col-sm-6">
                      <h1><span>E</span>-SHOPPER</h1>
                      <h2>{{product.title}}</h2>
                      <p>{{product.description}}</p>
                      <button type="button" class="btn btn-default get">Get it now</button>
                    </div>
                    <div class="col-sm-6">
                      <img src={{product.imageUrl}} class="girl img-responsive" alt="" />
                    </div>
                  </div>
                </ng-container>
              </ng-container>
            </div>
            <a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
              <i class="fa fa-angle-left"></i>
            </a>
            <a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
              <i class="fa fa-angle-right"></i>
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>
</ng-container>
