// Front-End Frameworks/Vue/ecommerce-Frond-End/src/components/core/Brand/Brand.vue
<template>
  <div class="col-sm-4">
    <div class="product-image-wrapper">
      <div class="single-products">
        <router-link
          :to="{ name: 'ProductsByBrand', params: { id: brand._id } }"
        >
          <div class="productinfo text-center">
            <img :src="brand.imageUrl" :alt="brand.name" />
            <p>{{ brand.name }}</p>
          </div>
        </router-link>
        <!-- isLoggedIn -->
        <div
          v-if="!!this.$store.state.users.isLoggedIn"
          class="product-overlay"
        >
          <div class="overlay-content">
            <h2>
              <router-link
                :to="'/brand-edit/' + brand._id"
                class="btn btn-default add-to-cart"
              >
                <i class="fa fa-edit"></i>
                Edit {{ brand.name }}
              </router-link>
            </h2>
            <h2>
              <router-link to="/" class="btn btn-default add-to-cart">
                <i class="fa fa-trash"></i>
                Delete {{ brand.name }}
              </router-link>
              <!-- <a
                (click)="deleteBrand(brand._id)"
                routerLink="/"
                class="btn btn-default add-to-cart"
              >
                <i class="fa fa-trash"></i>
                Delete {{ brand.name }}
              </a> -->
            </h2>
          </div>
        </div>
        <!-- /isLoggedIn -->
      </div>
    </div>
  </div>
</template>

<script src="./Brand.js"></script>

<style scoped src="./Brand.scss" lang="scss"></style>

// JS Web/ReactJS/React Project/ecommerce/src/components/brand/brand.js
import React from 'react';
import { Link } from 'react-router-dom';
import { StoreContext } from "../../globalFunctions/Store/Store";
import { deleteBrand } from '../../api';

const Brand = ({ brand }) => {
    const { state } = React.useContext(StoreContext);
    const isLoggedIn = !!state.user;

    return <div key={brand.webId} className="col-sm-4">
        <div className="product-image-wrapper">
            <div className="single-products">
                <Link to={`/brand/${brand._id}`} >
                    <div className="productinfo text-center">
                        <img src={brand.imageUrl} alt={brand.name} />
                        <p>{brand.name}</p>
                    </div>
                </Link>
                {isLoggedIn
                    ? < div className="product-overlay">
                        <div className="overlay-content">
                            <h2>
                                <Link to={`/brand-edit/${brand._id}`} className="btn btn-default add-to-cart">
                                    <i className="fa fa-edit"></i>Edit {brand.name}</Link>
                            </h2>
                            <h2>
                                <Link to='/' onClick={() => deleteBrand(brand)} className="btn btn-default add-to-cart deleteBtn">
                                    <i className="fa fa-trash"></i>Delete {brand.name}</Link>
                            </h2>
                        </div>
                    </div>
                    : null
                }
            </div>
        </div>
    </div >
}

export default Brand;
