// Front-End Frameworks/Angular/ecommerce-Front-End/e-commerce/src/app/core/category-component/category-component.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Category } from 'src/app/shared/interfaces';

@Component({
  selector: 'app-category-component',
  templateUrl: './category-component.component.html',
  styleUrls: ['./category-component.component.scss']
})
export class CategoryComponentComponent implements OnInit {
  @Input() category: Category;

  constructor() { }

  ngOnInit() {
  }

}

<div class="col-sm-4">
  <div class="product-image-wrapper">
    <div class="single-products">
      <a [routerLink]="['/brand', category._id]">
        <div class="productinfo text-center">
          <img src={{category.imageUrl}} alt={{category.name}} />
          <p>{{category.name}}</p>
        </div>
      </a>
      <!-- isLoggedIn -->
      <div class="product-overlay">
        <div class="overlay-content">
          <h2>
            <a routerLink='/brand-edit/{{category._id}}' class="btn btn-default add-to-cart">
              <i class="fa fa-edit"></i>Edit {{category.name}}</a>
          </h2>
          <h2>
            <a routerLink='/' class="btn btn-default add-to-cart">
              <i class="fa fa-trash"></i>Delete {{category.name}}</a>
          </h2>
        </div>
      </div>
      <!-- /isLoggedIn -->
    </div>
  </div>
</div>

// Front-End Frameworks/Vue/ecommerce-Frond-End/src/components/core/Category/Category.vue
<template>
  <div class="col-sm-4">
    <div class="product-image-wrapper">
      <div class="single-products">
        <router-link
          :to="{ name: 'ProductsByCategory', params: { id: category._id } }"
        >
          <div class="productinfo text-center">
            <img :src="category.imageUrl" :alt="category.name" />
            <p>{{ category.name }}</p>
          </div>
        </router-link>
        <!-- isLoggedIn -->
        <div
          v-if="!!this.$store.state.users.isLoggedIn"
          class="product-overlay"
        >
          <div class="overlay-content">
            <h2>
              <router-link
                :to="/brand-edit/ + category._id"
                class="btn btn-default add-to-cart"
              >
                <i class="fa fa-edit"></i>
                Edit {{ category.name }}
              </router-link>
            </h2>
            <h2>
              <router-link to="/" class="btn btn-default add-to-cart">
                <i class="fa fa-trash"></i>
                Delete {{ category.name }}
              </router-link>
              <!-- <router-link
                (click)="deleteCategory(category._id)"
                to="/"
                class="btn btn-default add-to-cart"
              >
                <i class="fa fa-trash"></i>
                Delete {{ category.name }}
              </router-link> -->
            </h2>
          </div>
        </div>
        <!-- /isLoggedIn -->
      </div>
    </div>
  </div>
</template>

<script src="./Category.js"></script>

<style scoped src="./Category.scss" lang="scss"></style>
