// JS Web/ReactJS/React Project/ecommerce/src/components/category/category.js
import React from 'react';
import { Link } from 'react-router-dom';
import { StoreContext } from "../../globalFunctions/Store/Store";
import { deleteCategory } from '../../api';

const Category = (props) => {
    const { state } = React.useContext(StoreContext);
    const isLoggedIn = !!state.user;
    const category = props.category;

    return <div key={category.webId} className="col-sm-4">
        <div className="product-image-wrapper">
            <div className="single-products">
                <div className="productinfo text-center">
                    <img src={category.imageUrl} alt={category.name} />
                    <p>{category.name}</p>
                </div>
                {isLoggedIn
                    ? <div className="product-overlay">
                        <div className="overlay-content">
                            <h2>
                                <Link to={`/category-edit/${category._id}`} className="btn btn-default add-to-cart">
                                    <i className="fa fa-edit"></i>Edit {category.name}</Link>
                            </h2>
                            <h2>
                                <Link to={`/`} onClick={() => deleteCategory(category)} className="btn btn-default add-to-cart deleteBtn">
                                    <i className="fa fa-trash"></i>Delete {category.name}</Link>
                            </h2>
                        </div>
                    </div>
                    : null
                }
            </div>
        </div>
    </div>
}

export default Category;

// Front-End Frameworks/Vue/ecommerce-Frond-End/src/components/core/Category/Category.vue
<template>
  <div class="col-sm-4">
    <div class="product-image-wrapper">
      <div class="single-products">
        <router-link
          :to="{ name: 'ProductsByCategory', params: { id: category._id } }"
        >
          <div class="productinfo text-center">
            <img :src="category.imageUrl" :alt="category.name" />
            <p>{{ category.name }}</p>
          </div>
        </router-link>
        <!-- isLoggedIn -->
        <div
          v-if="!!this.$store.state.users.isLoggedIn"
          class="product-overlay"
        >
          <div class="overlay-content">
            <h2>
              <router-link
                :to="/brand-edit/ + category._id"
                class="btn btn-default add-to-cart"
              >
                <i class="fa fa-edit"></i>
                Edit {{ category.name }}
              </router-link>
            </h2>
            <h2>
              <router-link to="/" class="btn btn-default add-to-cart">
                <i class="fa fa-trash"></i>
                Delete {{ category.name }}
              </router-link>
              <!-- <router-link
                (click)="deleteCategory(category._id)"
                to="/"
                class="btn btn-default add-to-cart"
              >
                <i class="fa fa-trash"></i>
                Delete {{ category.name }}
              </router-link> -->
            </h2>
          </div>
        </div>
        <!-- /isLoggedIn -->
      </div>
    </div>
  </div>
</template>

<script src="./Category.js"></script>

<style scoped src="./Category.scss" lang="scss"></style>
