// Front-End Frameworks/Vue/ecommerce-Frond-End/src/components/core/Product/Product.vue
<template>
  <div class="col-sm-4">
    <div class="product-image-wrapper">
      <div class="single-products">
        <div class="productinfo text-center">
          <img :src="product.imageUrl" :alt="product.title" />
          <h2>{{ product.price }}</h2>
          <p>{{ product.title }}</p>
          <router-link
            :to="'/product/' + product._id"
            class="btn btn-default add-to-cart"
          >
            <i class="fa fa-shopping-cart"></i>
            Product details
          </router-link>
        </div>
        <!-- <div v-fi="!!isLoggedIn" class="product-overlay">
          <div class="overlay-content">
            <h2>{{ product.price }}</h2>
            <p>{{ product.title }}</p>
            <router-link
              :to="['/product/', product._id]"
              class="btn btn-default add-to-cart"
              ><i class="fa fa-shopping-cart"></i>Product Details</router-link
            >
            <a
              (click)="deleteProduct(product._id)"
              class="btn btn-default add-to-cart"
              ><i class="fa fa-shopping-cart"></i>Delete {{ product.title }}</a
            >
          </div>
        </div> -->
      </div>
      <div class="choose">
        <ul class="nav nav-pills nav-justified">
          <li>
            <a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a>
          </li>
          <li>
            <a href="#"><i class="fa fa-plus-square"></i>Add to compare</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>

<script src="./Product.js"></script>

<style scoped src="./Product.scss" lang="scss"></style>

// JS Web/ReactJS/React Project/ecommerce/src/components/product/product.js
import React from 'react';
import { Link } from 'react-router-dom';

const Product = (props) => {
    const product = props.product;
    return <div key={product.webId} className="col-sm-4">
        <div className="product-image-wrapper">
            <div className="single-products">
                <div className="productinfo text-center">
                    <img src={product.imageUrl} alt="" />
                    <h2>${product.price}</h2>
                    <p>{product.title}</p>
                    <Link to="/" className="btn btn-default add-to-cart"><i
                        className="fa fa-shopping-cart"></i>Add to cart</Link>
                </div>
                <div className="product-overlay">
                    <div className="overlay-content">
                        <h2>${product.price}</h2>
                        <p>{product.title}</p>
                        <Link to="/" className="btn btn-default add-to-cart"><i
                            className="fa fa-shopping-cart"></i>Add to cart</Link>
                        <h2>
                            <Link to={`/product-details/${product._id}`} className="btn btn-default add-to-cart">
                                <i className="fa fa-info-circle"></i>Product Info</Link>
                        </h2>
                    </div>
                </div>
            </div>
            <div className="choose">
                <ul className="nav nav-pills nav-justified">
                    <li><Link to="/"><i className="fa fa-plus-square"></i>Add to wishlist</Link></li>
                    <li><Link to="/"><i className="fa fa-plus-square"></i>Add to compare</Link></li>
                </ul>
            </div>
        </div>
    </div>
}

export default Product;
