// Front-End Frameworks/Vue/ecommerce-Frond-End/src/components/pages/Home/Home.vue
<template>
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        <div class="left-sidebar">
          <!-- <app-category-side-bar [allCategories]="allCategories"></app-category-side-bar>
          <app-brands-side-bar [allBrands]="allBrands"></app-brands-side-bar>
          <app-price-range-side-bar></app-price-range-side-bar> -->
        </div>
      </div>
      <div class="col-sm-9 padding-right">
        <!-- <app-features-items [allProducts]="allProducts"></app-features-items>
        <app-category-tab [allCategories]="allCategories"></app-category-tab>
        <app-recommended-items [allProducts]="allProducts"></app-recommended-items> -->
      </div>
    </div>
  </div>
</template>

<script src="./Home"></script>
<style scoped></style>

// Front-End Frameworks/Angular/ecommerce-Front-End/e-commerce/src/app/pages/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { HomeService } from './home.service';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {

  get allProducts() {
    return this.homeService.products;
  }

  get allBrands() {
    return this.homeService.brands;
  }

  get allCategories() {
    return this.homeService.categories;
  }

  constructor(private homeService: HomeService) {
    this.homeService.getAllProducts();
    this.homeService.getAllBrands();
    this.homeService.getAllCategories();
  }

  ngOnInit() {

  }

}

<app-slider [allProducts]="allProducts"></app-slider>
<section>
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        <div class="left-sidebar">
          <app-category-side-bar [allCategories]="allCategories"></app-category-side-bar>
          <app-brands-side-bar [allBrands]="allBrands"></app-brands-side-bar>
          <app-price-range-side-bar></app-price-range-side-bar>
        </div>
      </div>
      <div class="col-sm-9 padding-right">
        <app-features-items [allProducts]="allProducts"></app-features-items>
        <app-category-tab></app-category-tab>
        <app-recommended-items></app-recommended-items>
      </div>
    </div>
  </div>
</section>
