// Front-End Frameworks/Vue/ecommerce-Frond-End/src/components/core/Brand/Brand.vue
<template>
  <div class="col-sm-4">
    <div class="product-image-wrapper">
      <div class="single-products">
        <router-link
          :to="{ name: 'ProductsByBrand', params: { id: brand._id } }"
        >
          <div class="productinfo text-center">
            <img :src="brand.imageUrl" :alt="brand.name" />
            <p>{{ brand.name }}</p>
          </div>
        </router-link>
        <!-- isLoggedIn -->
        <div
          v-if="!!this.$store.state.users.isLoggedIn"
          class="product-overlay"
        >
          <div class="overlay-content">
            <h2>
              <router-link
                :to="'/brand-edit/' + brand._id"
                class="btn btn-default add-to-cart"
              >
                <i class="fa fa-edit"></i>
                Edit {{ brand.name }}
              </router-link>
            </h2>
            <h2>
              <router-link to="/" class="btn btn-default add-to-cart">
                <i class="fa fa-trash"></i>
                Delete {{ brand.name }}
              </router-link>
              <!-- <a
                (click)="deleteBrand(brand._id)"
                routerLink="/"
                class="btn btn-default add-to-cart"
              >
                <i class="fa fa-trash"></i>
                Delete {{ brand.name }}
              </a> -->
            </h2>
          </div>
        </div>
        <!-- /isLoggedIn -->
      </div>
    </div>
  </div>
</template>

<script src="./Brand.js"></script>

<style scoped src="./Brand.scss" lang="scss"></style>

// Front-End Frameworks/Angular/ecommerce-Front-End/e-commerce/src/app/core/brand-component/brand-component.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Brand } from 'src/app/shared/interfaces/brand';

@Component({
  selector: 'app-brand-component',
  templateUrl: './brand-component.component.html',
  styleUrls: ['./brand-component.component.scss']
})
export class BrandComponentComponent implements OnInit {
  @Input() brand: Brand;

  constructor() { }

  ngOnInit() {
  }

}

<div class="col-sm-4">
  <div class="product-image-wrapper">
    <div class="single-products">
      <a [routerLink]="['/brand', brand._id]">
        <div class="productinfo text-center">
          <img src={{brand.imageUrl}} alt={{brand.name}} />
          <p>{{brand.name}}</p>
        </div>
      </a>
      <!-- isLoggedIn -->
      <div class="product-overlay">
        <div class="overlay-content">
          <h2>
            <a routerLink='/brand-edit/{{brand._id}}' class="btn btn-default add-to-cart">
              <i class="fa fa-edit"></i>Edit {{brand.name}}</a>
          </h2>
          <h2>
            <a routerLink='/' class="btn btn-default add-to-cart">
              <i class="fa fa-trash"></i>Delete {{brand.name}}</a>
          </h2>
        </div>
      </div>
      <!-- /isLoggedIn -->
    </div>
  </div>
</div>
