// JS Web/ReactJS/React Project/ecommerce/src/components/user/login/login.js
import React from 'react';
import './login.css';


const Login = () => (
    <div>
        <div className="col-sm-4 col-sm-offset-1">
            <div className="login-form">
                <h2>Login to your account</h2>
                <form action="#">
                    <input type="text" placeholder="Name" />
                    <input type="email" placeholder="Email Address" />
                    <span>
                        <input type="checkbox" className="checkbox" />
                        Keep me signed in
                </span>
                    <button type="submit" className="btn btn-default">Login</button>
                </form>
            </div>
        </div>
        <div className="col-sm-1">
            <h2 className="or">OR</h2>
        </div>
        <div className="col-sm-4">
            <div className="signup-form">
                <h2>New User Signup!</h2>
                <form action="#">
                    <input type="text" placeholder="Name" />
                    <input type="email" placeholder="Email Address" />
                    <input type="password" placeholder="Password" />
                    <input type="password" placeholder="Repeate password" />
                    <button type="submit" className="btn btn-default">Signup</button>
                </form>
            </div>
        </div>
    </div>
);

export default Login;

// Front-End Frameworks/Vue/ecommerce-Frond-End/src/components/core/Login/Login.vue
<template>
  <div class="login-form">
    <app-error-message
      :hasError="usernameError.state"
      :errorMessage="usernameError.errorMessage"
    />
    <app-error-message
      :hasError="passwordError.state"
      :errorMessage="passwordError.errorMessage"
    />
    <h2>Login to your account</h2>
    <form @submit.prevent="submitLogin">
      <!-- <form [formGroup]="loginForm" (ngSubmit)="onSubmitLogin()"> -->
      <input
        v-model="userName"
        type="text"
        placeholder="Name"
        autocomplete="on"
        @keyup="validateUsername()"
      />
      <input
        v-model="password"
        type="password"
        placeholder="Password"
        autocomplete="off"
        @keyup="validatePassword()"
      />
      <span>
        <input type="checkbox" class="checkbox" />
        Keep me signed in
      </span>
      <!-- <button type="submit" class="btn btn-default"> -->
      <button
        :disabled="usernameError.state || passwordError.state"
        type="submit"
        class="btn btn-default"
      >
        Login
      </button>
    </form>
  </div>
</template>

<script src="./Login"></script>
<style scoped src="./Login.scss" lang="scss"></style>
