// Front-End Frameworks/Vue/ecommerce-Frond-End/src/components/shared/Header/Header.vue
<template>
  <header id="header">
    <!--header-->
    <div class="header_top">
      <!--header_top-->
      <div class="container">
        <div class="row">
          <div class="col-sm-6">
            <div class="contactinfo">
              <ul class="nav nav-pills">
                <li>
                  <a routerLink=""
                    ><i class="fa fa-phone"></i> +2 95 01 88 821</a
                  >
                </li>
                <li>
                  <a routerLink=""
                    ><i class="fa fa-envelope"></i> info@domain.com</a
                  >
                </li>
              </ul>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="social-icons pull-right">
              <ul class="nav navbar-nav">
                <li>
                  <a routerLink=""><i class="fa fa-facebook"></i></a>
                </li>
                <li>
                  <a routerLink=""><i class="fa fa-twitter"></i></a>
                </li>
                <li>
                  <a routerLink=""><i class="fa fa-linkedin"></i></a>
                </li>
                <li>
                  <a routerLink=""><i class="fa fa-dribbble"></i></a>
                </li>
                <li>
                  <a routerLink=""><i class="fa fa-google-plus"></i></a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!--/header_top-->

    <div class="header-middle">
      <!--header-middle-->
      <div class="container">
        <div class="row">
          <div class="col-md-4 clearfix">
            <div class="logo pull-left">
              <a routerLink="/home"
                ><img src="../../../assets/images/home/logo.png" alt=""
              /></a>
            </div>
            <div class="btn-group pull-right clearfix">
              <div class="btn-group">
                <button
                  type="button"
                  class="btn btn-default dropdown-toggle usa"
                  data-toggle="dropdown"
                >
                  USA
                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                  <li><a routerLink="">Canada</a></li>
                  <li><a routerLink="">UK</a></li>
                </ul>
              </div>

              <div class="btn-group">
                <button
                  type="button"
                  class="btn btn-default dropdown-toggle usa"
                  data-toggle="dropdown"
                >
                  DOLLAR
                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                  <li><a routerLink="">Canadian Dollar</a></li>
                  <li><a routerLink="">Pound</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-md-8 clearfix">
            <div class="shop-menu clearfix pull-right">
              <ul class="nav navbar-nav">
                <li>
                  <a routerLink=""><i class="fa fa-user"></i> Account</a>
                </li>
                <li>
                  <a routerLink=""><i class="fa fa-star"></i> Wishlist</a>
                </li>
                <li>
                  <a routerLink=""><i class="fa fa-shopping-cart"></i> Cart</a>
                </li>
                <!-- <li *ngIf="!!isLoggedIn">
                  <a routerLink="">
                    <i class="fa fa-crosshairs"></i> Welcome,
                    {{ user?.userName }}</a
                  >
                </li> -->
                <li>
                  <!-- <a *ngIf="!isLoggedIn" routerLink="/login-register"
                    ><i class="fa fa-lock"></i> Login</a
                  > -->
                </li>
                <li>
                  <!-- <a
                    *ngIf="!!isLoggedIn"
                    (click)="logOut()"
                    routerLink="login-register"
                    ><i class="fa fa-lock"></i> Logout</a
                  > -->
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!--/header-middle-->

    <div class="header-bottom">
      <!--header-admin-->
      <div class="container">
        <div class="row">
          <div class="col-sm-9">
            <div class="mainmenu pull-left">
              <ul class="nav navbar-nav collapse navbar-collapse">
                <li>
                  <a routerLink="/home" routerLinkActive="active">Home</a>
                </li>
                <li>
                  <a routerLink="/shop" routerLinkActive="active">Shop</a>
                </li>
                <li>
                  <a routerLink="/brands" routerLinkActive="active">Brands</a>
                </li>
                <li>
                  <a routerLink="/categories" routerLinkActive="active"
                    >Categories</a
                  >
                </li>
              </ul>
            </div>
          </div>
          <div class="col-sm-3">
            <div class="search_box pull-right">
              <input type="text" placeholder="Search" />
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-9">
            <div class="mainmenu pull-left">
              <!-- <ul
                *ngIf="!!isLoggedIn"
                class="nav navbar-nav collapse navbar-collapse"
              >
                <li>
                  <a routerLink="/create-product" routerLinkActive="active"
                    >Create Product</a
                  >
                </li>
                <li>
                  <a routerLink="/create-brand" routerLinkActive="active"
                    >Create Brand</a
                  >
                </li>
                <li>
                  <a routerLink="/create-category" routerLinkActive="active"
                    >Create Category</a
                  >
                </li>
              </ul> -->
            </div>
          </div>
        </div>
      </div>
    </div>
    <!--/header-admin-->
  </header>
  <!--/header-->
</template>

<script src="./Header"></script>
<style lang="scss" src="./Header.scss" scoped></style>

// Front-End Frameworks/Angular/ecommerce-Front-End/e-commerce/src/app/core/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { UserService } from 'src/app/pages/user/user.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {

  constructor(private userService: UserService) { }

  ngOnInit() {
  }

  get logOut() {
    return this.userService.logout;
  }

  get isLoggedIn() {
    return this.userService.isLoggedIn;
  }

}

<header id="header">
  <!--header-->
  <div class="header_top">
    <!--header_top-->
    <div class="container">
      <div class="row">
        <div class="col-sm-6">
          <div class="contactinfo">
            <ul class="nav nav-pills">
              <li><a routerLink=""><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
              <li><a routerLink=""><i class="fa fa-envelope"></i> info@domain.com</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="social-icons pull-right">
            <ul class="nav navbar-nav">
              <li><a routerLink=""><i class="fa fa-facebook"></i></a></li>
              <li><a routerLink=""><i class="fa fa-twitter"></i></a></li>
              <li><a routerLink=""><i class="fa fa-linkedin"></i></a></li>
              <li><a routerLink=""><i class="fa fa-dribbble"></i></a></li>
              <li><a routerLink=""><i class="fa fa-google-plus"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--/header_top-->

  <div class="header-middle">
    <!--header-middle-->
    <div class="container">
      <div class="row">
        <div class="col-md-4 clearfix">
          <div class="logo pull-left">
            <a routerLink="index.html"><img src="../../../assets/images/home/logo.png" alt="" /></a>
          </div>
          <div class="btn-group pull-right clearfix">
            <div class="btn-group">
              <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                USA
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><a routerLink="">Canada</a></li>
                <li><a routerLink="">UK</a></li>
              </ul>
            </div>

            <div class="btn-group">
              <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                DOLLAR
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><a routerLink="">Canadian Dollar</a></li>
                <li><a routerLink="">Pound</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-8 clearfix">
          <div class="shop-menu clearfix pull-right">
            <ul class="nav navbar-nav">
              <li><a routerLink=""><i class="fa fa-user"></i> Account</a></li>
              <li><a routerLink=""><i class="fa fa-star"></i> Wishlist</a></li>
              <li><a routerLink="checkout.html"><i class="fa fa-crosshairs"></i> Checkout</a></li>
              <li><a routerLink="cart.html"><i class="fa fa-shopping-cart"></i> Cart</a></li>
              <li><a *ngIf="!isLoggedIn" routerLink="/login-register"><i class="fa fa-lock"></i> Login</a></li>
              <li><a *ngIf="isLoggedIn" (click)="logOut()" routerLink="/login-register"><i class="fa fa-lock"></i>
                  Logout</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--/header-middle-->

  <div class="header-bottom">
    <!--header-admin-->
    <div class="container">
      <div class="row">
        <div class="col-sm-9">
          <div class="mainmenu pull-left">
            <ul class="nav navbar-nav collapse navbar-collapse">
              <li><a routerLink="/home" routerLinkActive="active">Home</a></li>
              <li><a routerLink="/shop" routerLinkActive="active">Shop</a>
              <li><a routerLink="/brands" routerLinkActive="active">Brands</a>
              <li><a routerLink="/categories" routerLinkActive="active">Categories</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="search_box pull-right">
            <input type="text" placeholder="Search" />
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-9">
          <div class="mainmenu pull-left">
            <ul class="nav navbar-nav collapse navbar-collapse">
              <li><a routerLink="/create-product" routerLinkActive="active">Create Product</a></li>
              <li><a routerLink="/create-brand" routerLinkActive="active">Create Brand</a>
              <li><a routerLink="/create-category" routerLinkActive="active">Create Category</a>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--/header-admin-->
</header>
<!--/header-->
