// Front-End Frameworks/Angular/ecommerce-Front-End/e-commerce/src/app/core/category-tab/category-tab.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Category } from 'src/app/shared/interfaces';

@Component({
  selector: 'app-category-tab',
  templateUrl: './category-tab.component.html',
  styleUrls: ['./category-tab.component.scss']
})
export class CategoryTabComponent implements OnInit {
  @Input() allCategories: Category[];

  constructor() { }

  ngOnInit() {
  }

}

<div class="category-tab">
  <div class="col-sm-12">
    <ul class="nav nav-tabs">

      <li *ngFor="let category of allCategories" RouterLinkActive="active"><a [href]="['#'+category.name]"
          data-toggle="tab">{{category.name}}</a></li>

    </ul>
  </div>
  <div class="tab-content">

    <div *ngFor="let category of allCategories" class="tab-pane fade" RouterLinkActive="active" [id]="category.name">
      <ng-container *ngFor="let product of category.products">
        <app-product-small [product]="product"></app-product-small>
      </ng-container>
    </div>
  </div>
</div>

// Front-End Frameworks/Vue/ecommerce-Frond-End/src/components/core/CategoryTab/CategoryTab.vue
<template>
  <div class="category-tab">
    <div class="col-sm-12">
      <ul class="nav nav-tabs">
        <!-- <li *ngFor="let category of allCategories" RouterLinkActive="active">
          <a [href]="['#'+category.name]" data-toggle="tab">{{
            category.name
          }}</a>
        </li> -->
      </ul>
    </div>
    <div class="tab-content">
      <!-- <div
        *ngFor="let category of allCategories"
        class="tab-pane fade"
        RouterLinkActive="active"
        [id]="category.name"
      >
        <ng-container *ngFor="let product of category.products">
          <app-product-small [product]="product"></app-product-small>
        </ng-container>
      </div> -->
    </div>
  </div>
</template>

<script src="./CategoryTab.js"></script>

<style scoped src="./CategoryTab.scss" lang="scss"></style>
