// Front-End Frameworks/Vue/ecommerce-Frond-End/src/components/core/PriceRangeSideBar/PriceRangeSideBar.vue
<template>
  <div class="price-range">
    <!--price-range-->
    <h2>Price Range</h2>
    <div class="well text-center">
      <input
        type="text"
        class="span2"
        value=""
        data-slider-min="0"
        data-slider-max="600"
        data-slider-step="5"
        data-slider-value="[250,450]"
        id="sl2"
      /><br />
      <b class="pull-left">$ 0</b> <b class="pull-right">$ 600</b>
    </div>
  </div>
</template>

<script src="./PriceRangeSideBar.js"></script>

<style scoped src="./PriceRangeSideBar.scss" lang="scss"></style>

// Front-End Frameworks/Angular/ecommerce-Front-End/e-commerce/src/app/core/price-range-side-bar/price-range-side-bar.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-price-range-side-bar',
  templateUrl: './price-range-side-bar.component.html',
  styleUrls: ['./price-range-side-bar.component.scss']
})
export class PriceRangeSideBarComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="price-range">
  <!--price-range-->
  <h2>Price Range</h2>
  <div class="well text-center">
    <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5"
      data-slider-value="[250,450]" id="sl2"><br />
    <b class="pull-left">$ 0</b> <b class="pull-right">$ 600</b>
  </div>
</div>
