// Front-End Frameworks/Angular/ecommerce-Front-End/e-commerce/src/app/core/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { UserService } from 'src/app/pages/user/user.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {

  constructor(private userService: UserService) { }

  ngOnInit() {
  }

  get logOut() {
    return this.userService.logout;
  }

  get isLoggedIn() {
    return this.userService.isLoggedIn;
  }

}

<header id="header">
  <!--header-->
  <div class="header_top">
    <!--header_top-->
    <div class="container">
      <div class="row">
        <div class="col-sm-6">
          <div class="contactinfo">
            <ul class="nav nav-pills">
              <li><a routerLink=""><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
              <li><a routerLink=""><i class="fa fa-envelope"></i> info@domain.com</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="social-icons pull-right">
            <ul class="nav navbar-nav">
              <li><a routerLink=""><i class="fa fa-facebook"></i></a></li>
              <li><a routerLink=""><i class="fa fa-twitter"></i></a></li>
              <li><a routerLink=""><i class="fa fa-linkedin"></i></a></li>
              <li><a routerLink=""><i class="fa fa-dribbble"></i></a></li>
              <li><a routerLink=""><i class="fa fa-google-plus"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--/header_top-->

  <div class="header-middle">
    <!--header-middle-->
    <div class="container">
      <div class="row">
        <div class="col-md-4 clearfix">
          <div class="logo pull-left">
            <a routerLink="index.html"><img src="../../../assets/images/home/logo.png" alt="" /></a>
          </div>
          <div class="btn-group pull-right clearfix">
            <div class="btn-group">
              <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                USA
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><a routerLink="">Canada</a></li>
                <li><a routerLink="">UK</a></li>
              </ul>
            </div>

            <div class="btn-group">
              <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                DOLLAR
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><a routerLink="">Canadian Dollar</a></li>
                <li><a routerLink="">Pound</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-8 clearfix">
          <div class="shop-menu clearfix pull-right">
            <ul class="nav navbar-nav">
              <li><a routerLink=""><i class="fa fa-user"></i> Account</a></li>
              <li><a routerLink=""><i class="fa fa-star"></i> Wishlist</a></li>
              <li><a routerLink="checkout.html"><i class="fa fa-crosshairs"></i> Checkout</a></li>
              <li><a routerLink="cart.html"><i class="fa fa-shopping-cart"></i> Cart</a></li>
              <li><a *ngIf="!isLoggedIn" routerLink="/login-register"><i class="fa fa-lock"></i> Login</a></li>
              <li><a *ngIf="isLoggedIn" (click)="logOut()" routerLink="/login-register"><i class="fa fa-lock"></i>
                  Logout</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--/header-middle-->

  <div class="header-bottom">
    <!--header-admin-->
    <div class="container">
      <div class="row">
        <div class="col-sm-9">
          <div class="mainmenu pull-left">
            <ul class="nav navbar-nav collapse navbar-collapse">
              <li><a routerLink="/home" routerLinkActive="active">Home</a></li>
              <li><a routerLink="/shop" routerLinkActive="active">Shop</a>
              <li><a routerLink="/brands" routerLinkActive="active">Brands</a>
              <li><a routerLink="/categories" routerLinkActive="active">Categories</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="search_box pull-right">
            <input type="text" placeholder="Search" />
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-9">
          <div class="mainmenu pull-left">
            <ul class="nav navbar-nav collapse navbar-collapse">
              <li><a routerLink="/create-product" routerLinkActive="active">Create Product</a></li>
              <li><a routerLink="/create-brand" routerLinkActive="active">Create Brand</a>
              <li><a routerLink="/create-category" routerLinkActive="active">Create Category</a>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--/header-admin-->
</header>
<!--/header-->

// Front-End Frameworks/Vue/ecommerce-Frond-End/src/components/core/Header/Header.vue
<template>
  <header id="header">
    <!--header-->
    <div class="header_top">
      <!--header_top-->
      <div class="container">
        <div class="row">
          <div class="col-sm-6">
            <div class="contactinfo">
              <ul class="nav nav-pills">
                <li>
                  <router-link to="">
                    <i class="fa fa-phone"></i> +2 95 01 88 821
                  </router-link>
                </li>
                <li>
                  <router-link to=""
                    ><i class="fa fa-envelope"></i> info@domain.com
                  </router-link>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="social-icons pull-right">
              <ul class="nav navbar-nav">
                <li>
                  <router-link to=""
                    ><i class="fa fa-facebook"></i
                  ></router-link>
                </li>
                <li>
                  <router-link to=""><i class="fa fa-twitter"></i></router-link>
                </li>
                <li>
                  <router-link to=""
                    ><i class="fa fa-linkedin"></i
                  ></router-link>
                </li>
                <li>
                  <router-link to=""
                    ><i class="fa fa-dribbble"></i
                  ></router-link>
                </li>
                <li>
                  <router-link to=""
                    ><i class="fa fa-google-plus"></i
                  ></router-link>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!--/header_top-->

    <div class="header-middle">
      <!--header-middle-->
      <div class="container">
        <div class="row">
          <div class="col-md-4 clearfix">
            <div class="logo pull-left">
              <router-link to="/home"
                ><img src="../../../assets/images/home/logo.png" alt=""
              /></router-link>
            </div>
            <div class="btn-group pull-right clearfix">
              <div class="btn-group">
                <button
                  type="button"
                  class="btn btn-default dropdown-toggle usa"
                  data-toggle="dropdown"
                >
                  USA
                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                  <li><router-link to="">Canada</router-link></li>
                  <li><router-link to="">UK</router-link></li>
                </ul>
              </div>

              <div class="btn-group">
                <button
                  type="button"
                  class="btn btn-default dropdown-toggle usa"
                  data-toggle="dropdown"
                >
                  DOLLAR
                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                  <li>
                    <router-link to="">Canadian Dollar</router-link>
                  </li>
                  <li><router-link to="">Pound</router-link></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-md-8 clearfix">
            <div class="shop-menu clearfix pull-right">
              <ul class="nav navbar-nav">
                <li>
                  <router-link to=""
                    ><i class="fa fa-user"></i> Account</router-link
                  >
                </li>
                <li>
                  <router-link to=""
                    ><i class="fa fa-star"></i> Wishlist</router-link
                  >
                </li>
                <li>
                  <router-link to=""
                    ><i class="fa fa-shopping-cart"></i> Cart</router-link
                  >
                </li>
                <li v-if="isLoggedIn">
                  <router-link to="">
                    <i class="fa fa-crosshairs"></i> Welcome,
                    {{ userName }}
                  </router-link>
                </li>
                <li>
                  <router-link
                    v-if="!isLoggedIn"
                    to="/login-register"
                    @click="login()"
                    ><i class="fa fa-lock"></i> Login</router-link
                  >
                </li>
                <li>
                  <router-link v-if="isLoggedIn" to="/login-register"
                    ><i class="fa fa-lock"></i>
                    <span @click="logOut()"> Logout </span>
                  </router-link>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!--/header-middle-->

    <div class="header-bottom">
      <!--header-admin-->
      <div class="container">
        <div class="row">
          <div class="col-sm-9">
            <div class="mainmenu pull-left">
              <ul class="nav navbar-nav collapse navbar-collapse">
                <li>
                  <router-link to="/home" routerLinkActive="active"
                    >Home</router-link
                  >
                </li>
                <li>
                  <router-link to="/shop" routerLinkActive="active"
                    >Shop</router-link
                  >
                </li>
                <li>
                  <router-link to="/brands" routerLinkActive="active"
                    >Brands</router-link
                  >
                </li>
                <li>
                  <router-link to="/categories" routerLinkActive="active"
                    >Categories</router-link
                  >
                </li>
              </ul>
            </div>
          </div>
          <div class="col-sm-3">
            <div class="search_box pull-right">
              <input type="text" placeholder="Search" />
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-9">
            <div class="mainmenu pull-left">
              <!-- <ul
                *ngIf="!!isLoggedIn"
                class="nav navbar-nav collapse navbar-collapse"
              >
                <li>
                  <router-link to="/create-product" routerLinkActive="active"
                    >Create Product</router-link>
                </li>
                <li>
                  <router-link to="/create-brand" routerLinkActive="active">Create Brand</router-link>
                </li>
                <li>
                  <router-link to="/create-category" routerLinkActive="active">Create Category</router-link>
                </li>
              </ul> -->
            </div>
          </div>
        </div>
      </div>
    </div>
    <!--/header-admin-->
  </header>
  <!--/header-->
</template>

<script src="./Header"></script>
<style lang="scss" src="./Header.scss" scoped></style>
