// Front-End Frameworks/Vue/ecommerce-Frond-End/src/components/core/ProductSmall/ProductSmall.vue
<template>
  <div class="col-sm-3">
    <div class="product-image-wrapper">
      <div class="single-products">
        <div class="productinfo text-center">
          <img :src="product.imageUrl" :alt="product.title" />
          <h2>{{ product.price }}</h2>
          <p>{{ product.title }}</p>
          <router-link to="#" class="btn btn-default add-to-cart">
            <i class="fa fa-shopping-cart"></i>
            Add to cart
          </router-link>
        </div>
        <!-- <div *ngIf="!!isLoggedIn" class="product-overlay">
          <div class="overlay-content">
            <h2>{{ product.price }}</h2>
            <p>{{ product.title }}</p>
            <a href="#" class="btn btn-default add-to-cart"
              ><i class="fa fa-shopping-cart"></i>Add to cart</a
            >
          </div>
        </div> -->
      </div>
      <div class="choose">
        <ul class="nav nav-pills nav-justified">
          <li>
            <a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a>
          </li>
          <li>
            <a href="#"><i class="fa fa-plus-square"></i>Add to compare</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>

<script src="./ProductSmall.js"></script>

<style scoped src="./ProductSmall.scss" lang="scss"></style>

// Front-End Frameworks/Angular/ecommerce-Front-End/e-commerce/src/app/core/product-small/product-small.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Product } from 'src/app/shared/interfaces';

@Component({
  selector: 'app-product-small',
  templateUrl: './product-small.component.html',
  styleUrls: ['./product-small.component.scss']
})
export class ProductSmallComponent implements OnInit {
  @Input() product: Product;

  constructor() { }

  ngOnInit() {
  }

}

<div class="col-sm-3">
  <div class="product-image-wrapper">
    <div class="single-products">
      <div class="productinfo text-center">
        <img [src]="product.imageUrl" [alt]="product.title" />
        <h2>{{product.price}}</h2>
        <p>{{product.title}}</p>
        <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
      </div>
      <div class="product-overlay">
        <div class="overlay-content">
          <h2>{{product.price}}</h2>
          <p>{{product.title}}</p>
          <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
        </div>
      </div>
    </div>
    <div class="choose">
      <ul class="nav nav-pills nav-justified">
        <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
        <li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
      </ul>
    </div>
  </div>
</div>
