// JS Web/ReactJS/React Project/ecommerce/src/components/slider/slider.js
import React, { Fragment, useEffect, useState } from 'react';
import { getAllProducts } from '../../api';
import Loader from '../../components/propmts/loader/loader';

const Slider = () => {
    const [products, setProducts] = useState([]);

    useEffect(() => {
        getAllProducts()
            .then(res => setProducts(res))
            .catch(err => console.log(err))
    }, [])


    return <section id="slider">
        <div className="container">
            <div className="row">
                <div className="col-sm-12">
                    <div id="slider-carousel" className="carousel slide" data-ride="carousel">
                        <ol className="carousel-indicators">
                            <li data-target="#slider-carousel" data-slide-to="0" className="active"></li>
                            <li data-target="#slider-carousel" data-slide-to="1"></li>
                            <li data-target="#slider-carousel" data-slide-to="2"></li>
                        </ol>
                        <div className="carousel-inner">
                            {!!products.length
                                ? products
                                    .filter(product => product.recommended === true)
                                    .map((product, index) => <div key={product.webId} className={index === 0 ? 'item active' : 'item'}>
                                        <div className="col-sm-6">
                                            <h1><span>E</span>-SHOPPER</h1>
                                            <h2>{product.name}</h2>
                                            <p>{product.description} </p>
                                            <button type="button" className="btn btn-default get">Get it now</button>
                                        </div>
                                        <div className="col-sm-6">
                                            <img src={product.imageUrl} className="girl img-responsive" alt={product.name} />
                                            <img src="images/home/pricing.png" className="pricing" alt="" />
                                        </div>
                                    </div>)
                                : <Loader />
                            }
                        </div>
                        <a href="#slider-carousel" className="left control-carousel hidden-xs" data-slide="prev">
                            <i className="fa fa-angle-left"></i>
                        </a>
                        <a href="#slider-carousel" className="right control-carousel hidden-xs" data-slide="next">
                            <i className="fa fa-angle-right"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
};

export default Slider;

// Front-End Frameworks/Vue/ecommerce-Frond-End/src/components/core/Slider/Slider.vue
<template>
  <div>
    <template v-if="!allProducts">
      <span>No products to display in the slider section!</span>
    </template>
    <template v-if="allProducts">
      <section id="slider">
        <div class="container">
          <div class="row">
            <div class="col-sm-12">
              <div
                id="slider-carousel"
                class="carousel slide"
                data-ride="carousel"
              >
                <ol class="carousel-indicators">
                  <template
                    v-for="(product, num) in allProducts"
                    :key="product._id"
                  >
                    <template v-if="product.onSlider">
                      <li
                        attr.data-slide-to="num"
                        data-target="#slider-carousel"
                      >
                        {{ num }}
                      </li>
                      <!-- <li
                        :attr.data-slide-to="num"
                        data-target="#slider-carousel"
                        [class.active]="num===0"
                         routerLinkActive="active"
                      ></li> -->
                    </template>
                  </template>
                </ol>
                <div class="carousel-inner">
                  <template
                    *ngFor="let product of allProducts; let num = index;"
                  >
                    <template v-if="product.onSlider === true">
                      <div
                        class="item"
                        [class.active]="num===0"
                        routerLinkActive="active"
                      >
                        <div class="col-sm-6">
                          <h1><span>E</span>-SHOPPER</h1>
                          <h2>{{ product.title }}</h2>
                          <p>{{ product.description }}</p>
                          <button type="button" class="btn btn-default get">
                            Get it now
                          </button>
                        </div>
                        <div class="col-sm-6">
                          <img
                            src="{{product.imageUrl}}"
                            class="girl img-responsive"
                            alt=""
                          />
                        </div>
                      </div>
                    </template>
                  </template>
                </div>
                <a
                  href="#slider-carousel"
                  class="left control-carousel hidden-xs"
                  data-slide="prev"
                >
                  <i class="fa fa-angle-left"></i>
                </a>
                <a
                  href="#slider-carousel"
                  class="right control-carousel hidden-xs"
                  data-slide="next"
                >
                  <i class="fa fa-angle-right"></i>
                </a>
              </div>
            </div>
          </div>
        </div>
      </section>
    </template>
  </div>
</template>

<script src="./Slider.js"></script>

<style src="./Slider.scss" lang="scss"></style>
