// Front-End Frameworks/Angular/ecommerce-Front-End/e-commerce/src/app/pages/create-product-page/create-product-page.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormControl, FormBuilder, Validators } from '@angular/forms';
import { ViewEncapsulation } from '@angular/core';
import { CreateProductPageService } from './create-product-page.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-create-product-page',
  templateUrl: './create-product-page.component.html',
  styleUrls: ['./create-product-page.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class CreateProductPageComponent implements OnInit {

  options: FormGroup;
  hideRequiredControl = new FormControl(false);
  floatLabelControl = new FormControl('auto');
  panelColor = new FormControl('yellow');

  constructor(fb: FormBuilder, private createProductService: CreateProductPageService, private router: Router) {
    this.options = fb.group({
      hideRequired: this.hideRequiredControl,
      floatLabel: this.floatLabelControl,
    });
    this.createProductService.getAllBrands();
    this.createProductService.getAllCategories();
  }

  createProductForm = new FormGroup({
    title: new FormControl('', [Validators.required]),
    webId: new FormControl('', [Validators.required]),
    price: new FormControl('', [Validators.required]),
    description: new FormControl('', [Validators.required]),
    imageUrl: new FormControl('', [Validators.required]),
    condition: new FormControl('', [Validators.required]),
    availability: new FormControl(''),
    onSlider: new FormControl(''),
    featuredItem: new FormControl(''),
    recommended: new FormControl(''),
    brand: new FormControl('', [Validators.required]),
    category: new FormControl('', [Validators.required]),
  });

  onSubmit() {
    this.createProductService.createProduct(this.createProductForm.value)
    this.router.navigate(['/shop']);
  }

  get allBrands() {
    return this.createProductService.brands;
  }

  get allCategories() {
    return this.createProductService.categories;
  }

  ngOnInit() {
  }

  get checkTitle() { return !!(this.createProductForm.get('title').errors && (this.createProductForm.get('title').touched || this.createProductForm.get('title').dirty)) }
  get checkWebId() { return !!(this.createProductForm.get('webId').errors && (this.createProductForm.get('webId').touched || this.createProductForm.get('webId').dirty)) }
  get checkPrice() { return !!(this.createProductForm.get('price').errors && (this.createProductForm.get('price').touched || this.createProductForm.get('price').dirty)) }
  get checkDescription() { return !!(this.createProductForm.get('description').errors && (this.createProductForm.get('description').touched || this.createProductForm.get('description').dirty)) }
  get checkImageUrl() { return !!(this.createProductForm.get('imageUrl').errors && (this.createProductForm.get('imageUrl').touched || this.createProductForm.get('imageUrl').dirty)) }
  get checkCondition() { return !!(this.createProductForm.get('condition').errors && (this.createProductForm.get('condition').touched || this.createProductForm.get('condition').dirty)) }
  get checkBrand() { return !!(this.createProductForm.get('brand').errors && (this.createProductForm.get('brand').touched || this.createProductForm.get('brand').dirty)) }
  get checkCategory() { return !!(this.createProductForm.get('category').errors && (this.createProductForm.get('category').touched || this.createProductForm.get('category').dirty)) }

}

<div class="example-container">
  <form [formGroup]="createProductForm" (ngSubmit)="onSubmit()">
    <mat-form-field appearance="fill" [floatLabel]="floatLabelControl.value">
      <mat-label>Product Name</mat-label>
      <input formControlName="title" matInput placeholder="Please enter a name minimum 4 character long">
      <app-error-message *ngIf="checkTitle" errorMessage="Title is reqired!"></app-error-message>
    </mat-form-field>
    <mat-form-field appearance="fill" [floatLabel]="floatLabelControl.value">
      <mat-label>Art. number:</mat-label>
      <input formControlName="webId" type="number" matInput placeholder="Please enter a name minimum 4 character long">
      <app-error-message *ngIf="checkWebId" errorMessage="Art. number is reqired!"></app-error-message>
    </mat-form-field>
    <mat-form-field appearance="fill" [floatLabel]="floatLabelControl.value">
      <mat-label>Price:</mat-label>
      <input formControlName="price" type="number" matInput placeholder="Please enter a price">
      <app-error-message *ngIf="checkPrice" errorMessage="Price is reqired!"></app-error-message>
    </mat-form-field>
    <mat-form-field appearance="fill" [floatLabel]="floatLabelControl.value">
      <mat-label>Condition:</mat-label>
      <input formControlName="condition" matInput placeholder="Please enter a condition">
      <app-error-message *ngIf="checkCondition" errorMessage="Condition is reqired!"></app-error-message>
    </mat-form-field>
    <mat-form-field>
      <mat-label>Brand:</mat-label>
      <mat-select formControlName="brand" panelClass="example-panel-yellow">
        <mat-option *ngFor="let brand of allBrands" value={{brand._id}}>{{brand.name}}</mat-option>
      </mat-select>
      <app-error-message *ngIf="checkBrand" errorMessage="Please pick a Brand!"></app-error-message>
    </mat-form-field>
    <mat-form-field>
      <mat-label>Category:</mat-label>
      <mat-select formControlName="category" panelClass="example-panel-yellow">
        <mat-option *ngFor="let category of allCategories" value={{category._id}}>{{category.name}}</mat-option>
      </mat-select>
      <app-error-message *ngIf="checkCategory" errorMessage="Please pick a Category!"></app-error-message>
    </mat-form-field>
    <mat-form-field class="example-full-width">
      <mat-label>Description:</mat-label>
      <textarea formControlName="description" matInput placeholder="Ex. It makes me feel..."></textarea>
      <app-error-message *ngIf="checkDescription" errorMessage="Please enter a description!"></app-error-message>
    </mat-form-field>
    <div class="checkbox">
      <mat-checkbox formControlName="availability">Product is available</mat-checkbox>
      <mat-checkbox formControlName="featuredItem">Product is featured</mat-checkbox>
      <mat-checkbox formControlName="recommended">Product is recommended</mat-checkbox>
      <mat-checkbox formControlName="onSlider">Product is on the slider</mat-checkbox>
    </div>
    <br />
    <mat-form-field appearance="fill" [floatLabel]="floatLabelControl.value">
      <mat-label>Image URL</mat-label>
      <input formControlName="imageUrl" matInput placeholder="Please enter a name minimum 4 character long">
      <app-error-message *ngIf="checkImageUrl" errorMessage="Url of a image is reqired!"></app-error-message>
    </mat-form-field>
    <button [disabled]="createProductForm.invalid" class="btn btn-default">Create Brand</button>
  </form>
</div>

// Front-End Frameworks/Vue/ecommerce-Frond-End/src/components/pages/CreateProductPage/CreateProductPage.vue
<template>
  <div>
    <div class="example-container">
      <label>Product Name</label>
      <input
        v-model="title"
        matInput
        placeholder="Please enter a name minimum 4 character long"
      />
      <!-- <error-message
          v-if="checkTitle"
          errorMessage="Title is reqired!"
        ></error-message> -->
      <label>Art. number:</label>
      <input
        v-model="webId"
        type="number"
        matInput
        placeholder="Please enter a name minimum 4 character long"
      />
      <!-- <error-message
          *ngIf="checkWebId"
          errorMessage="Art. number is reqired!"
        ></error-message> -->
      <label>Price:</label>
      <input
        v-model="price"
        type="number"
        matInput
        placeholder="Please enter a price"
      />
      <!-- <error-message
          *ngIf="checkPrice"
          errorMessage="Price is reqired!"
        ></error-message> -->
      <label>Condition:</label>
      <input
        v-model="condition"
        matInput
        placeholder="Please enter a condition"
      />
      <!-- <error-message
          *ngIf="checkCondition"
          errorMessage="Condition is reqired!"
        ></error-message> -->
      <label>Brand:</label>
      <select v-model="brand" panelClass="example-panel-yellow">
        <option v-for="brand in allBrands" :key="brand._id" :value="brand._id">
          {{ brand.name }}
        </option>
      </select>
      <!-- <error-message
          *ngIf="checkBrand"
          errorMessage="Please pick a Brand!"
        ></error-message> -->
      <label>Category:</label>
      <select v-model="category" panelClass="example-panel-yellow">
        <option
          v-for="category in allCategories"
          :key="category._id"
          :value="category._id"
        >
          {{ category.name }}
        </option>
      </select>
      <!-- <error-message
          *ngIf="checkCategory"
          errorMessage="Please pick a Category!"
        ></error-message> -->
      <label>Description:</label>
      <textarea
        v-model="description"
        matInput
        placeholder="Ex. It makes me feel..."
      ></textarea>
      <!-- <error-message
          *ngIf="checkDescription"
          errorMessage="Please enter a description!"
        ></error-message> -->
      <div class="checkbox">
        <label>Product is available</label>
        <input type="checkbox" v-model="availability" />
        <br />
        <label>Product is featured</label>
        <input type="checkbox" v-model="featuredItem" />
        <br />
        <label>Product is recommended</label>
        <input type="checkbox" v-model="recommended" />
        <br />
        <label>Product is on the slider</label>
        <input type="checkbox" v-model="onSlider" />
        <br />
      </div>
      <br />
      <label>Image URL</label>
      <input
        v-model="imageUrl"
        matInput
        placeholder="Please enter a name minimum 4 character long"
      />
      <!-- <error-message
            *ngIf="checkImageUrl"
            errorMessage="Url of a image is reqired!"
          ></error-message> -->
      <button @click="createProduct()" class="btn btn-default">
        Create Product
      </button>
    </div>
  </div>
</template>

<script src="./CreateProductPage"></script>
<style scoped src="./CreateProductPage.scss" lang="scss"></style>
