// Front-End Frameworks/Angular/ecommerce-Front-End/e-commerce/src/app/pages/shop/shop.component.ts
import { Component, OnInit } from '@angular/core';
import { ShopService } from "./shop.service";

@Component({
  selector: 'app-shop',
  templateUrl: './shop.component.html',
  styleUrls: ['./shop.component.scss']
})
export class ShopComponent implements OnInit {

  get allProducts() {
    return this.shopService.products;
  }

  constructor(private shopService: ShopService) {
    this.shopService.getAllProducts();
  }

  ngOnInit() {
  }


}

<section>
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        <div class="left-sidebar">
          <app-category-side-bar></app-category-side-bar>
          <app-brands-side-bar></app-brands-side-bar>
          <app-price-range-side-bar></app-price-range-side-bar>
        </div>
      </div>
      <div class="col-sm-9 padding-right">
        <ng-container *ngFor="let product of allProducts">
          <app-product [product]="product"></app-product>
        </ng-container>
      </div>
    </div>
  </div>
</section>

// Front-End Frameworks/Vue/ecommerce-Frond-End/src/components/pages/Shop/Shop.vue
<template>
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        <div class="left-sidebar">
          <category-side-bar :allCategories="allCategories" />
          <brand-side-bar :allBrands="allBrands" />
          <price-range-sideBar />
        </div>
      </div>
      <div class="col-sm-9 padding-right">
        <div v-for="product in allProducts" :key="product._id">
          <product :product="product"></product>
        </div>
      </div>
    </div>
  </div>
</template>

<script src="./Shop"></script>
<style scoped src="./Shop.scss" lang="scss"></style>
